#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    exclude = []

    test_upgrade_from.9e9d8e3ae23d3c1817d6a8ef6ae4a33370defa82.name = "v3.15.0~ynh3 (manifestv1 - old_version_for_CI_1)"

    test_upgrade_from.9b82e772d59aa586dd2e0d5c7e9adac09f2d030e.name = "v3.15.0~ynh4 (pre refactoring)"
