#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    exclude = []

    test_upgrade_from.97c374cc07fc5f2eea38f79c0876836d334752aa.name = "v3.15.0~ynh3 (manifestv1 - old_version_for_CI_1)"
    test_upgrade_from.b05d95387b6606b0f7a23db1060a8a2b89405ac4.name = "v3.15.0~ynh4 (pre refactoring) (old_version_for_CI_2 branch)"
    test_upgrade_from.810906aa07cb6a4ed4502f1466b781644cc6e1a8.name = "Before helper 2.1 (old_version_for_CI_3 branch)"
