#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers
load_vars

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
if systemctl is-active "$app".service --quiet; then
    ynh_print_warn "It's highly recommended to make your backup when the service is stopped. Please stop $app service with this command before to run the backup 'systemctl stop $app.service'"
fi

ynh_print_info "Declaring files to be backed up..."

#=================================================
# BACKUP THE NGINX CONFIGURATION
#=================================================

ynh_backup "/etc/$app/"
ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_backup "$nginx_status_conf"

ynh_print_info "Backing up code..."
ynh_backup "$install_dir"

#=================================================
# SPECIFIC BACKUP
#=================================================
# BACKUP SYSTEMD
#=================================================

ynh_backup "/etc/systemd/system/$app.service"

#=================================================
# BACKUP VARIOUS FILES
#=================================================

ynh_backup "$data_dir"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
