#!/bin/bash
# In simple cases, you don't need a config script.

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source ./_common.sh
source /usr/share/yunohost/helpers
source ./experimental_helper.sh

ynh_abort_if_errors

ynh_app_config_apply() {
    _ynh_app_config_apply
    load_vars
    ynh_add_jinja_config --template=monitorix.conf --destination="/etc/monitorix/monitorix.conf"
    save_vars_current_value
}

#=================================================
# GENERIC FINALIZATION
#=================================================
ynh_app_config_run "$1"
